baseurl = "https://papamufflon.github.io/The-hugo-desktop-blog/"
languageCode = "en-us"
title = "The hugo-desktop blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
# googleAnalytics = ""
theme = "hugo-minimalist-theme"


[params]
    site_author = "Tobias Walter"
    site_description = "The hugo-desktop blog"
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "The hugo-desktop blog"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    # google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "PapaMufflon"
    # facebook  = ""
    # linkedin  = ""
    # behance   = ""
    # dribbble  = ""
    # instagram = ""
    github    = "papamufflon"
    # gplus     = ""
